# Generated by Django 5.0.6 on 2024-08-07 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MultiScheme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAPI',
            fields=[
                ('Id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_number', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='active', max_length=20, null=True)),
                ('fund_type', models.CharField(max_length=50)),
                ('_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('exited_date', models.DateTimeField(blank=True, null=True)),
                ('exited_flag', models.BooleanField(default=False)),
                ('profit', models.FloatField(default=0.0)),
                ('subscription_date', models.DateField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('investment_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.investmentscheme')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('employee_amount', models.FloatField()),
                ('employer_amount', models.FloatField()),
                ('retro_employee_amount', models.FloatField()),
                ('retro_employer_amount', models.FloatField()),
                ('contribution_date', models.DateTimeField()),
                ('investment_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.investmentscheme')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.staffapi')),
            ],
        ),
    ]
