# Generated by Django 5.0.2 on 2024-05-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionsDetails',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeNo', models.PositiveIntegerField()),
                ('Fundtype', models.IntegerField()),
                ('EmployeeAmount', models.PositiveIntegerField()),
                ('EmployerAmount', models.PositiveIntegerField()),
                ('RetroEmployeeAmount', models.PositiveIntegerField()),
                ('RetroEmployerAmount', models.PositiveIntegerField()),
                ('Employee55Amount', models.PositiveIntegerField()),
                ('Employer55Amount', models.PositiveIntegerField()),
                ('RetroEmployee55Amount', models.PositiveIntegerField()),
                ('RetroEmployer55Amount', models.PositiveIntegerField()),
                ('ContributionDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
