# Generated by Django 5.0.7 on 2024-08-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiScheme', '0005_alter_investmentscheme_id'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.investmentscheme'),
        ),
        migrations.AddField(
            model_name='staffapi',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.investmentscheme'),
        ),
    ]
