# Generated by Django 5.0.2 on 2024-05-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionsdetails',
            name='EmployeeId',
        ),
        migrations.AlterField(
            model_name='contributionsdetails',
            name='EmployeeNo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
