# Generated by Django 5.0.2 on 2024-06-19 09:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionsDetail',
            fields=[
                ('EmployeeNo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Fundtype', models.IntegerField()),
                ('EmployeeAmount', models.FloatField()),
                ('EmployerAmount', models.FloatField()),
                ('RetroEmployeeAmount', models.FloatField()),
                ('RetroEmployerAmount', models.FloatField()),
                ('Employee55Amount', models.FloatField()),
                ('Employer55Amount', models.FloatField()),
                ('RetroEmployee55Amount', models.FloatField()),
                ('RetroEmployer55Amount', models.FloatField()),
                ('ContributionDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_date', models.DateField(default=django.utils.timezone.now)),
                ('total_contributions_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_contributions_b', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_contributions_c', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_contributions_d', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAPI',
            fields=[
                ('Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=255)),
                ('Staffnumber', models.IntegerField()),
                ('Datejoined', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('Fundtype', models.CharField(max_length=50)),
                ('EmployeeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EmployerAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RetroEmployeeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RetroEmployerAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Employee55Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Employer55Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RetroEmployee55Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RetroEmployer55Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ContributionDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('staff_number', models.CharField(max_length=100, unique=True)),
                ('date_joined', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('separated', 'Separated')], default='active', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ContributionsDetails',
        ),
        migrations.AddField(
            model_name='generalledger',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='contributions.staffmember'),
        ),
    ]
