# Generated by Django 5.0.6 on 2024-08-01 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiScheme', '0004_alter_tenant_id'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.tenant'),
        ),
        migrations.AddField(
            model_name='staffapi',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.tenant'),
        ),
    ]
