# Generated by Django 5.0.6 on 2024-07-11 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('employee_amount', models.FloatField()),
                ('employer_amount', models.FloatField()),
                ('retro_employee_amount', models.FloatField()),
                ('retro_employer_amount', models.FloatField()),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAPI',
            fields=[
                ('Id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_number', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='active', max_length=20, null=True)),
                ('fund_type', models.CharField(max_length=50)),
                ('employee_amount', models.FloatField()),
                ('employer_amount', models.FloatField()),
                ('retro_employee_amount', models.FloatField()),
                ('retro_employer_amount', models.FloatField()),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_date', models.DateTimeField(blank=True, null=True)),
                ('exited_flag', models.BooleanField(default=False)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('subscription_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContributionsDetails',
        ),
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.staffapi'),
        ),
    ]
