# Generated by Django 5.0.6 on 2024-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_staffapi_delete_contributionsdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='contribution_date',
            field=models.DateTimeField(),
        ),
    ]
