# Generated by Django 5.0.2 on 2024-05-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_remove_contributionsdetails_employeeid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContributionsDetails',
            new_name='ContributionsDetail',
        ),
    ]
