# Generated by Django 5.0.2 on 2024-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contributionsdetail_generalledger_staffapi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapi',
            name='ExitedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffapi',
            name='ExitedFlag',
            field=models.BooleanField(default=False),
        ),
    ]
