# Generated by Django 5.0.2 on 2024-06-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_staffapi_exiteddate_staffapi_exitedflag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralLedger',
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
