# Generated by Django 5.0.6 on 2024-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_rename_contributionsdetails_contributionsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionsdetail',
            name='Employee55Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributionsdetail',
            name='EmployeeAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributionsdetail',
            name='Employer55Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributionsdetail',
            name='EmployerAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributionsdetail',
            name='RetroEmployee55Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributionsdetail',
            name='RetroEmployeeAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributionsdetail',
            name='RetroEmployer55Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributionsdetail',
            name='RetroEmployerAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contributionsdetail',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
