# Generated by Django 5.0.6 on 2024-08-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiScheme', '0004_alter_tenant_id'),
        ('contributions', '0003_remove_contribution_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffapi',
            name='tenant',
        ),
        migrations.AddField(
            model_name='staffapi',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.investmentscheme'),
        ),
    ]
