# Generated by Django 5.0.6 on 2024-07-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_alter_staffapi_contribution_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffapi',
            name='contribution_date',
        ),
        migrations.RemoveField(
            model_name='staffapi',
            name='employee_amount',
        ),
        migrations.RemoveField(
            model_name='staffapi',
            name='employer_amount',
        ),
        migrations.RemoveField(
            model_name='staffapi',
            name='retro_employee_amount',
        ),
        migrations.RemoveField(
            model_name='staffapi',
            name='retro_employer_amount',
        ),
    ]
