# Generated by Django 5.0.2 on 2024-06-05 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_alter_contributionsdetail_employee55amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('staff_number', models.CharField(max_length=100, unique=True)),
                ('date_joined', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('separated', 'Separated')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_date', models.DateField(default=django.utils.timezone.now)),
                ('total_contributions_a', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_contributions_b', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_contributions_c', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_contributions_d', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.staffmember')),
            ],
        ),
    ]
