# Generated by Django 5.0.2 on 2024-06-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_delete_generalledger_delete_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('employee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retro_employee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retro_employer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_55_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_55_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retro_employee_55_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retro_employer_55_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.staffapi')),
            ],
        ),
    ]
