# Generated by Django 5.0.6 on 2024-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_remove_staffapi_contribution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contribution_date',
            field=models.DateTimeField(),
        ),
    ]
