# Generated by Django 5.0.6 on 2024-07-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_alter_contribution_contribution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapi',
            name='_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
