# Generated by Django 5.0.2 on 2024-06-07 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_staffmember_generalledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAPI',
            fields=[
                ('Fullname', models.CharField(max_length=50)),
                ('Staffnumber', models.IntegerField()),
                ('Datejoined', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('Fundtype', models.CharField(max_length=50)),
                ('EmployeeAmount', models.FloatField()),
                ('EmployerAmount', models.FloatField()),
                ('RetroEmployeeAmount', models.FloatField()),
                ('RetroEmployerAmount', models.FloatField()),
                ('Employee55Amount', models.FloatField()),
                ('Employer55Amount', models.FloatField()),
                ('RetroEmployee55Amount', models.FloatField()),
                ('RetroEmployer55Amount', models.FloatField()),
                ('ContributionDate', models.DateField(auto_now_add=True)),
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='contributions.staffmember'),
        ),
    ]
