# Generated by Django 5.0.2 on 2024-06-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='contribution_date',
            new_name='ContributionDate',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='employee_55_amount',
            new_name='Employee55Amount',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='employee_amount',
            new_name='EmployeeAmount',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='employer_55_amount',
            new_name='Employer55Amount',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='employer_amount',
            new_name='EmployerAmount',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='retro_employee_55_amount',
            new_name='RetroEmployee55Amount',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='retro_employee_amount',
            new_name='RetroEmployeeAmount',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='retro_employer_55_amount',
            new_name='RetroEmployer55Amount',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='retro_employer_amount',
            new_name='RetroEmployerAmount',
        ),
    ]
