# Generated by Django 5.0.2 on 2024-06-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_rename_contribution_date_contribution_contributiondate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContributionsDetail',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='ContributionDate',
            field=models.DateTimeField(),
        ),
    ]
