# Generated by Django 5.0.6 on 2024-07-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_staffapi__amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='subscription_date',
            field=models.DateField(),
        ),
    ]
