# Generated by Django 5.0.2 on 2024-06-07 15:35

import contributions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_staffapi_alter_generalledger_staff_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='ContributionDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='Employee55Amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='EmployeeAmount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='Employer55Amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='EmployerAmount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='Id',
            field=contributions.models.IntegerUUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployee55Amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployeeAmount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployer55Amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployerAmount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='status',
            field=models.IntegerField(),
        ),
    ]
