# Generated by Django 5.0.6 on 2024-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_staffapi__amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
