# Generated by Django 5.0.6 on 2024-07-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_alter_staffapi_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='profit',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
