# Generated by Django 5.0.2 on 2024-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_delete_contributionsdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffapi',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
