# Generated by Django 5.0.2 on 2024-06-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_staffapi_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffapi',
            name='month',
        ),
    ]
