# Generated by Django 5.0.6 on 2024-07-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_alter_staffapi_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
    ]
