# Generated by Django 5.0.6 on 2024-07-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_alter_staffapi__amount'),
        ('contributions', '0009_alter_staffapi_profit'),
    ]

    operations = [
    ]
