# Generated by Django 5.0.2 on 2024-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_remove_staffapi_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='Id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
