# Generated by Django 5.0.6 on 2024-07-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_merge_20240723_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='subscription_date',
            field=models.DateTimeField(),
        ),
    ]
