# Generated by Django 5.0.6 on 2024-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0011_alter_staffapi_employee55amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffapi',
            name='Employee55Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='EmployeeAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='Employer55Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='EmployerAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='ExitedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='ExitedFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='Fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='Fundtype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='Id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployee55Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployeeAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployer55Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployerAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='Staffnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='status',
            field=models.IntegerField(),
        ),
    ]
