# Generated by Django 5.0.6 on 2024-07-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0012_alter_staffapi_employee55amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='Employee55Amount',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='Employer55Amount',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='RetroEmployee55Amount',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='RetroEmployer55Amount',
        ),
        migrations.RemoveField(
            model_name='staffapi',
            name='Employee55Amount',
        ),
        migrations.RemoveField(
            model_name='staffapi',
            name='Employer55Amount',
        ),
        migrations.RemoveField(
            model_name='staffapi',
            name='RetroEmployee55Amount',
        ),
        migrations.RemoveField(
            model_name='staffapi',
            name='RetroEmployer55Amount',
        ),
    ]
