# Generated by Django 5.0.6 on 2024-07-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_remove_contribution_employee55amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='EmployeeAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='EmployerAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='RetroEmployeeAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='RetroEmployerAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='EmployeeAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='EmployerAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployeeAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='staffapi',
            name='RetroEmployerAmount',
            field=models.FloatField(),
        ),
    ]
