# Generated by Django 5.0.2 on 2024-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='staff_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='tel_number',
            field=models.PositiveIntegerField(),
        ),
    ]
