# Generated by Django 5.0.6 on 2024-07-31 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_member_staff_id_alter_member_tel_number'),
        ('MultiScheme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.tenant'),
        ),
    ]
