# Generated by Django 5.0.6 on 2024-07-01 15:03

import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_member_staff_id_alter_member_tel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='otp_secret',
            field=models.CharField(default=django_otp.util.random_hex, max_length=16),
        ),
    ]
