# Generated by Django 5.0.6 on 2024-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_member_otp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
