# Generated by Django 5.0.6 on 2024-07-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
