# Generated by Django 5.0.6 on 2024-08-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiScheme', '0003_alter_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
