# Generated by Django 5.0.6 on 2024-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_role_description_role_permissions_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(help_text='Specific permissions for this user.', related_name='admin_user_permissions_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
