# Generated by Django 5.0.7 on 2024-08-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_user_user_permissions'),
        ('MultiScheme', '0005_alter_investmentscheme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.tenant'),
        ),
    ]
