# Generated by Django 5.0.6 on 2024-05-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.IntegerField(unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('interest_percentage', models.IntegerField()),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('interest_start_date', models.DateTimeField()),
                ('interest_end_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
