# Generated by Django 5.0.6 on 2024-07-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('GCB', 'GCB'), ('ADB', 'ADB'), ('CBG', 'CBG'), ('HFC', 'HFC'), ('Ecobank', 'Ecobank'), ('ABSA', 'ABSA')], default='GCB', max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('account_number', models.PositiveIntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('amount', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=50)),
                ('_status', models.CharField(default='Not used', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DelayedInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('amount', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=50)),
                ('_status', models.CharField(default='Not used', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('Current', 'Current'), ('Checking', 'Checking'), ('Savings', 'Savings'), ('Fixed Deposit', 'Fixed Deposit'), ('Premium Checking', 'Premium Checking'), ('Business', 'Business')], default='Current', max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('account_number', models.IntegerField(unique=True)),
                ('principal_amount', models.FloatField()),
                ('interest_percentage', models.FloatField()),
                ('rollover_interest_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('interest_start_date', models.DateField()),
                ('interest_end_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('roll_over', models.CharField(choices=[('ROLLOVER', 'Roll Over'), ('END', 'End'), ('NULL', 'null')], default='NULL', max_length=15)),
                ('_remaining_days', models.PositiveIntegerField(default=0)),
                ('_status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('staff_id', models.PositiveIntegerField(unique=True)),
                ('total_amount_to_date', models.FloatField(blank=True)),
                ('profit', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=20, null=True)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
