# Generated by Django 5.0.6 on 2024-07-31 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0001_initial'),
        ('MultiScheme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='bankinterest',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_interest', to='MultiScheme.investmentscheme'),
        ),
        migrations.AddField(
            model_name='delayedinterest',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delayed_interest', to='MultiScheme.investmentscheme'),
        ),
        migrations.AddField(
            model_name='investmentdetail',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_detail', to='MultiScheme.investmentscheme'),
        ),
    ]
