# Generated by Django 5.0.6 on 2024-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0002_rename_investmentdetails_investmentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdetail',
            name='investment_type',
            field=models.CharField(default='T-bill', max_length=50),
            preserve_default=False,
        ),
    ]
