# Generated by Django 5.0.6 on 2024-08-01 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0002_delete_member_bankinterest_investment_scheme_and_more'),
        ('MultiScheme', '0004_alter_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinterest',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.investmentscheme'),
        ),
        migrations.AlterField(
            model_name='delayedinterest',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.investmentscheme'),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='investment_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MultiScheme.investmentscheme'),
        ),
    ]
