# Generated by Django 5.0.6 on 2024-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0003_investmentdetail_investment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('staff_id', models.IntegerField(unique=True)),
                ('total_amount_to_date', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
