# Generated by Django 5.0.6 on 2024-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0003_alter_bankinterest_investment_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='investment_type',
            field=models.CharField(choices=[('Treasury Bill', 'Treasury Bill'), ('Fixed Deposit', 'Fixed Deposit')], default='Treasury Bill', max_length=50),
        ),
    ]
