# Generated by Django 5.0.6 on 2024-05-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0004_members_alter_investmentdetail_interest_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
