# Generated by Django 5.0.6 on 2024-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0005_rename_members_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='staff_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
