# Generated by Django 5.0.6 on 2024-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0006_alter_member_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='active', max_length=20),
            preserve_default=False,
        ),
    ]
