# Generated by Django 5.0.6 on 2024-05-22 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0007_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
