# Generated by Django 5.0.6 on 2024-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0008_member_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_amount_to_date',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
