# Generated by Django 5.0.6 on 2024-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0009_alter_member_profit_alter_member_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='total_amount_to_date',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
