# Generated by Django 5.0.6 on 2024-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0010_alter_member_total_amount_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
