# Generated by Django 5.0.6 on 2024-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0011_alter_member_profit_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
