# Generated by Django 5.0.2 on 2024-05-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0012_member_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeNo', models.PositiveIntegerField()),
                ('fundtype', models.IntegerField()),
                ('EmployeeAmount', models.PositiveIntegerField()),
                ('EmployerAmount', models.PositiveIntegerField()),
                ('RetroEmployeeAmount', models.PositiveIntegerField()),
                ('RetroEmployerAmount', models.PositiveIntegerField()),
                ('Employee55Amount', models.PositiveIntegerField()),
                ('Employer55Amount', models.PositiveIntegerField()),
                ('RetroEmployee55Amount', models.PositiveIntegerField()),
                ('RetroEmployer55Amount', models.PositiveIntegerField()),
            ],
        ),
    ]
