# Generated by Django 5.0.6 on 2024-05-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0012_member_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_start_date',
            field=models.DateField(),
        ),
    ]
