# Generated by Django 5.0.2 on 2024-05-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0013_contributions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributions',
        ),
    ]
