# Generated by Django 5.0.6 on 2024-05-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0013_alter_investmentdetail_interest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
