# Generated by Django 5.0.6 on 2024-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0014_alter_investmentdetail_interest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
