# Generated by Django 5.0.6 on 2024-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0014_delete_contributions'),
        ('Fund', '0015_alter_investmentdetail_interest_amount'),
    ]

    operations = [
    ]
