# Generated by Django 5.0.6 on 2024-05-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0016_merge_20240529_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdetail',
            name='roll_over',
            field=models.CharField(choices=[('ROLLOVER', 'Roll Over'), ('END', 'End'), ('NULL', 'null')], default='NULL', max_length=15),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
