# Generated by Django 5.0.6 on 2024-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0017_investmentdetail_roll_over_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdetail',
            name='rollover_interest_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
