# Generated by Django 5.0.6 on 2024-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0018_investmentdetail_rollover_interest_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='interest_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='principal_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investmentdetail',
            name='rollover_interest_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
