# Generated by Django 5.0.6 on 2024-06-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0019_alter_investmentdetail_interest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentdetail',
            name='interest_amount',
        ),
    ]
