# Generated by Django 5.0.6 on 2024-06-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0020_remove_investmentdetail_interest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='total_amount_to_date',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
