# Generated by Django 5.0.6 on 2024-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0021_alter_member_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='total_amount_to_date',
            field=models.FloatField(blank=True, default=200),
            preserve_default=False,
        ),
    ]
