# Generated by Django 5.0.6 on 2024-06-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0022_alter_member_total_amount_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
