# Generated by Django 5.0.6 on 2024-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0023_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=20, null=True),
        ),
    ]
