# Generated by Django 5.0.6 on 2024-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0024_alter_member_profit_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdetail',
            name='_remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
