# Generated by Django 5.0.6 on 2024-06-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0025_investmentdetail__remaining_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='_remaining_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
