# Generated by Django 5.0.6 on 2024-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0026_alter_investmentdetail__remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdetail',
            name='_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
