# Generated by Django 5.0.6 on 2024-06-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0027_investmentdetail__status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
