# Generated by Django 5.0.6 on 2024-07-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0028_alter_investmentdetail_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('GCB', 'GCB'), ('ADB', 'ADB'), ('CBG', 'CBG'), ('HFC', 'HFC'), ('Ecobank', 'Ecobank'), ('ABSA', 'ABSA')], default='GCB', max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('amount', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DelayedInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('amount', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
    ]
