# Generated by Django 5.0.6 on 2024-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0029_bankinterest_delayedinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='account_type',
            field=models.CharField(choices=[('Current', 'Current'), ('Checking', 'Checking'), ('Savings', 'Savings'), ('Fixed Deposit', 'Fixed Deposit'), ('Premium Checking', 'Premium Checking'), ('Business', 'Business')], default='Current', max_length=50),
        ),
    ]
