# Generated by Django 5.0.6 on 2024-07-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0030_alter_investmentdetail_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinterest',
            name='amount',
            field=models.FloatField(),
        ),
    ]
