# Generated by Django 5.0.6 on 2024-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0031_alter_bankinterest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinterest',
            name='bank_name',
            field=models.CharField(choices=[('GCB', 'GCB'), ('ADB', 'ADB'), ('CBG', 'CBG'), ('HFC', 'HFC'), ('Ecobank', 'Ecobank'), ('ABSA', 'ABSA')], default='GCB', max_length=20),
        ),
    ]
