# Generated by Django 5.0.6 on 2024-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0032_alter_bankinterest_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinterest',
            name='branch',
            field=models.CharField(default='accra', max_length=50),
            preserve_default=False,
        ),
    ]
