# Generated by Django 5.0.6 on 2024-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0033_bankinterest_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinterest',
            name='account_number',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
