# Generated by Django 5.0.6 on 2024-07-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0034_bankinterest_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinterest',
            name='_status',
            field=models.CharField(default='Not used', max_length=20),
        ),
        migrations.AddField(
            model_name='delayedinterest',
            name='_status',
            field=models.CharField(default='Not used', max_length=20),
        ),
    ]
